---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - betterstack.everadaptive.tech
  resources:
  - ingressmonitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - betterstack.everadaptive.tech
  resources:
  - ingressmonitors/finalizers
  verbs:
  - update
- apiGroups:
  - betterstack.everadaptive.tech
  resources:
  - ingressmonitors/status
  verbs:
  - get
  - patch
  - update
